# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information

[sncast.deployer]
account = "deployer"
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_9/0qrlR3sK-Gx07Fl9VhtCS"
wait-params = { timeout = 300, retry-interval = 10 }
block-explorer = "StarkScan"
show-explorer-links = true